name: Bug
description: Report a bug with Banana+.
title: '[Bug] '
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: |
        A clear and concise description of what the issue is.
        Provide as much information as possible: videos, crash reports, etc.
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to Reproduce
      description: How do you trigger this bug? Be as descriptive as possible.
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a bug report
      options:
        - label: |
            This bug wasn't already reported.
            (I have checked every bug report on GitHub.)
          required: true
        - label: |
            This is a valid bug.
            (This happens on the latest release.)
          required: true
